import { User, Plant, Diagnosis, PlantTimelineEvent, CarePlanTask, KnowledgeItem, ModelMetadata, Invoice } from './schema';

export const SEED_USERS: User[] = [
  {
    id: "usr_admin_001",
    email: "admin@plantinia.app",
    passwordHash: "pbkdf2_sha256$310000$ccea1f5744937f55fd3b8bb900fbcf03$aedb5a00547b36e7e23862a9f7fce0546aacb87efc599d5cfefd345310964ebc",
    name: "Dr. Elena Vance",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80",
    role: "admin",
    isEmailVerified: true,
    subscriptionTier: "farm",
    subscriptionStatus: "active",
    subscriptionCurrentPeriodEnd: new Date(Date.now() + 365 * 24 * 3600 * 1000).toISOString(),
    paymentProvider: "razorpay",
    subscriptionId: "sub_admin_annual",
    creditsRemaining: 9999,
    apiKey: "plnt_live_8f3910cbe4a991820",
    createdAt: new Date(Date.now() - 90 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "usr_demo_002",
    email: "demo@plantinia.app",
    passwordHash: "pbkdf2_sha256$310000$ccea1f5744937f55fd3b8bb900fbcf03$aedb5a00547b36e7e23862a9f7fce0546aacb87efc599d5cfefd345310964ebc",
    name: "Aarav Sharma",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80",
    role: "user",
    isEmailVerified: true,
    subscriptionTier: "pro",
    subscriptionStatus: "active",
    subscriptionCurrentPeriodEnd: new Date(Date.now() + 28 * 24 * 3600 * 1000).toISOString(),
    paymentProvider: "razorpay",
    subscriptionId: "sub_rzp_99218204",
    creditsRemaining: 48,
    apiKey: "plnt_live_7a810bce90471",
    createdAt: new Date(Date.now() - 30 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  }
];

export const SEED_PLANTS: Plant[] = [
  {
    id: "plt_monstera_01",
    userId: "usr_demo_002",
    name: "Living Room Monstera",
    species: "Monstera deliciosa",
    commonName: "Swiss Cheese Plant",
    imageUrl: "https://images.unsplash.com/photo-1614594975525-e45190c55d0b?w=600&auto=format&fit=crop&q=80",
    location: "indoor",
    healthStatus: "warning",
    sunlightNeeds: "indirect",
    wateringFrequencyDays: 7,
    lastWateredDate: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
    nextWateringDate: new Date(Date.now() + 2 * 24 * 3600 * 1000).toISOString(),
    notes: "New fenestrated leaf unfurling. Showing faint yellow margins on lower foliage.",
    createdAt: new Date(Date.now() - 45 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "plt_tomato_02",
    userId: "usr_demo_002",
    name: "Balcony Roma Tomato",
    species: "Solanum lycopersicum",
    commonName: "Tomato",
    imageUrl: "https://images.unsplash.com/photo-1592841200221-a6898f307baa?w=600&auto=format&fit=crop&q=80",
    location: "balcony",
    healthStatus: "critical",
    sunlightNeeds: "direct",
    wateringFrequencyDays: 2,
    lastWateredDate: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
    nextWateringDate: new Date(Date.now() + 1 * 24 * 3600 * 1000).toISOString(),
    notes: "Rapid dark water-soaked spots appeared after heavy monsoon rain.",
    createdAt: new Date(Date.now() - 25 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "plt_fiddle_03",
    userId: "usr_demo_002",
    name: "Office Fiddle Leaf Fig",
    species: "Ficus lyrata",
    commonName: "Fiddle-Leaf Fig",
    imageUrl: "https://images.unsplash.com/photo-1545241047-6083a3684587?w=600&auto=format&fit=crop&q=80",
    location: "indoor",
    healthStatus: "healthy",
    sunlightNeeds: "indirect",
    wateringFrequencyDays: 10,
    lastWateredDate: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
    nextWateringDate: new Date(Date.now() + 8 * 24 * 3600 * 1000).toISOString(),
    notes: "Growing vigorously near east-facing glass window.",
    createdAt: new Date(Date.now() - 60 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "plt_basil_04",
    userId: "usr_demo_002",
    name: "Kitchen Sweet Basil",
    species: "Ocimum basilicum",
    commonName: "Sweet Basil",
    imageUrl: "https://images.unsplash.com/photo-1608686207856-001b95cf60ca?w=600&auto=format&fit=crop&q=80",
    location: "indoor",
    healthStatus: "healthy",
    sunlightNeeds: "direct",
    wateringFrequencyDays: 3,
    lastWateredDate: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
    nextWateringDate: new Date(Date.now() + 2 * 24 * 3600 * 1000).toISOString(),
    notes: "Pinched flower buds to stimulate leafy vegetative growth.",
    createdAt: new Date(Date.now() - 15 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  }
];

export const SEED_DIAGNOSES: Diagnosis[] = [
  {
    id: "diag_roma_late_blight",
    userId: "usr_demo_002",
    plantId: "plt_tomato_02",
    mediaType: "image",
    mediaUrl: "https://images.unsplash.com/photo-1592841200221-a6898f307baa?w=600&auto=format&fit=crop&q=80",
    identifiedSpecies: "Solanum lycopersicum (Tomato)",
    diseaseName: "Tomato Late Blight (Phytophthora infestans)",
    pathogenType: "fungal",
    confidence: 96.4,
    severity: "severe",
    symptoms: [
      "Large irregular dark brown/black water-soaked lesions on foliage",
      "White fungal downy growth on the underside of infected leaves in humid weather",
      "Stems show dark brown greasy streaks",
      "Fruit develops firm, rough, bronze-brown patches"
    ],
    causes: [
      "High ambient relative humidity (>85%) combined with temperatures between 15°C and 22°C",
      "Prolonged leaf wetness from overhead watering or continuous rain",
      "Wind-blown sporangia from nearby infected nightshades"
    ],
    prognosis: "Treatable if intercepted immediately. Without intervention, entire plant defoliation will occur within 7 to 10 days.",
    treatmentSteps: [
      {
        stepNumber: 1,
        title: "Immediate Sanitation & Quarantine",
        instruction: "Prune all visibly infected leaves and stems using shears sanitized in 70% isopropyl alcohol. Bag and discard in trash; DO NOT compost.",
        frequency: "Immediate",
        isComplete: true,
      },
      {
        stepNumber: 2,
        title: "Foliar Fungicide Application",
        instruction: "Spray Copper Octanoate (Copper Soap) or Mancozeb thoroughly over both upper and lower leaf surfaces during early morning.",
        frequency: "Repeat every 5-7 days",
        isComplete: false,
      },
      {
        stepNumber: 3,
        title: "Watering & Airflow Adjustment",
        instruction: "Shift to drip or bottom watering to keep foliage completely dry. Stake branches to optimize canopy aeration.",
        frequency: "Permanent ongoing",
        isComplete: false,
      }
    ],
    organicRemedies: [
      "Baking Soda & Neem Spray: 1 tbsp baking soda + 1 tsp cold-pressed neem oil + 1/2 tsp liquid castile soap per 1 liter lukewarm water. Spray weekly.",
      "Bio-fungicide: Bacillus subtilis (Serenade) foliar spray to outcompete oomycete colonization."
    ],
    chemicalRemedies: [
      {
        name: "Copper Fungicide Liquid (Copper Diammonia Diacetate)",
        activeIngredient: "Copper Octanoate 0.08%",
        approximateCost: "₹280 / $6.50",
        instructions: "Mix 15ml per liter of water. Spray thoroughly every 7 days until no new lesions appear."
      },
      {
        name: "Mancozeb 75% WP (Dithane M-45)",
        activeIngredient: "Mancozeb 75%",
        approximateCost: "₹350 / $8.00",
        instructions: "2g per liter. Protective contact fungicide for high-outbreak monsoon periods."
      }
    ],
    preventativeMeasures: [
      "Apply 2 inches of organic straw mulch around plant base to prevent soil splash.",
      "Maintain minimum 2-foot plant spacing for cross-breeze airflow.",
      "Grow certified blight-resistant cultivars (e.g., 'Mountain Magic', 'Defiant')."
    ],
    boundingBoxes: [
      { x: 22, y: 35, width: 42, height: 38, label: "Late Blight Necrotic Zone" },
      { x: 58, y: 15, width: 25, height: 28, label: "Sporulating Margin" }
    ],
    aiProviderUsed: "gemini-1.5-flash",
    adminReviewed: true,
    adminAccuracyFeedback: "accurate",
    createdAt: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
  }
];

export const SEED_TIMELINE_EVENTS: PlantTimelineEvent[] = [
  {
    id: "evt_001",
    plantId: "plt_tomato_02",
    userId: "usr_demo_002",
    eventType: "diagnosis",
    title: "AI Disease Scan: Late Blight Detected",
    description: "Detected severe fungal lesion activity with 96.4% confidence.",
    imageUrl: "https://images.unsplash.com/photo-1592841200221-a6898f307baa?w=600&auto=format&fit=crop&q=80",
    createdAt: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: "evt_002",
    plantId: "plt_tomato_02",
    userId: "usr_demo_002",
    eventType: "pruning",
    title: "Infected Lower Canopy Pruned",
    description: "Sanitized 4 infected branches with isopropyl alcohol shears and bagged safely.",
    createdAt: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: "evt_003",
    plantId: "plt_monstera_01",
    userId: "usr_demo_002",
    eventType: "watering",
    title: "Deep Hydration & Foliar Dusting",
    description: "Watered with 1.2L filtered water until runoff. Wiped leaves with microfiber cloth.",
    createdAt: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
  }
];

export const SEED_CARE_TASKS: CarePlanTask[] = [
  {
    id: "tsk_01",
    userId: "usr_demo_002",
    plantId: "plt_tomato_02",
    plantName: "Balcony Roma Tomato",
    title: "Apply Copper Fungicide spray (Step 2 of Blight Protocol)",
    category: "spray",
    dueDate: new Date().toISOString().split('T')[0],
    isCompleted: false,
    notes: "Apply before 9 AM before sun becomes intense.",
    createdAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
  },
  {
    id: "tsk_02",
    userId: "usr_demo_002",
    plantId: "plt_monstera_01",
    plantName: "Living Room Monstera",
    title: "Check soil moisture at 2-inch depth",
    category: "water",
    dueDate: new Date().toISOString().split('T')[0],
    isCompleted: true,
    notes: "Top layer almost dry. Water tomorrow morning.",
    createdAt: new Date(Date.now() - 48 * 3600 * 1000).toISOString(),
  },
  {
    id: "tsk_03",
    userId: "usr_demo_002",
    plantId: "plt_fiddle_03",
    plantName: "Office Fiddle Leaf Fig",
    title: "Rotate pot 90 degrees for symmetrical sun exposure",
    category: "inspect",
    dueDate: new Date(Date.now() + 24 * 3600 * 1000).toISOString().split('T')[0],
    isCompleted: false,
    notes: "Helps prevent leaning towards the east window.",
    createdAt: new Date().toISOString(),
  }
];

export const SEED_KNOWLEDGE_BASE: KnowledgeItem[] = [
  {
    id: "kb_01",
    name: "Tomato Late Blight",
    type: "disease",
    scientificName: "Phytophthora infestans",
    category: "disease",
    affectedPlants: ["Tomato", "Potato", "Eggplant", "Nightshades"],
    symptoms: ["Water-soaked dark lesions", "White sporulation underneath leaves", "Greasy stem cankers"],
    treatment: "Isolate, prune infected tissue immediately, apply copper fungicide or Mancozeb. Avoid overhead watering.",
    prevention: "Mulch generously, increase row spacing, use certified disease-free seeds and resistant varieties.",
    imageUrl: "https://images.unsplash.com/photo-1592841200221-a6898f307baa?w=600&auto=format&fit=crop&q=80",
    isActive: true,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "kb_02",
    name: "Powdery Mildew",
    type: "disease",
    scientificName: "Podosphaera pannosa",
    category: "disease",
    affectedPlants: ["Rose", "Cucumbers", "Zucchini", "Apples", "Monstera", "Grapes"],
    symptoms: ["White powdery talcum-like coating on upper leaf surface", "Leaf curling and stunted buds"],
    treatment: "Potassium bicarbonate spray, neem oil solution, or sulfur dust. Apply early in infection cycle.",
    prevention: "Provide bright sunlight, proper pruning for air circulation, avoid high nitrogen fertilizing.",
    imageUrl: "https://images.unsplash.com/photo-1588628566587-dbd176de94b4?w=600&auto=format&fit=crop&q=80",
    isActive: true,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "kb_03",
    name: "Two-Spotted Spider Mites",
    type: "pest",
    scientificName: "Tetranychus urticae",
    category: "pest",
    affectedPlants: ["Houseplants", "Tomatoes", "Peppers", "Fruit trees", "Roses"],
    symptoms: ["Fine stippling / tiny yellow dots on leaves", "Delicate webbing between stems and petioles", "Bronze faded leaves"],
    treatment: "Blast foliage with water jet, apply insecticidal soap or horticultural oil, release predatory mites (Phytoseiulus persimilis).",
    prevention: "Maintain humidity above 50%, avoid dry dusty conditions, inspect leaf undersides regularly.",
    imageUrl: "https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?w=600&auto=format&fit=crop&q=80",
    isActive: true,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "kb_04",
    name: "Root Rot (Pythium / Phytophthora)",
    type: "disease",
    scientificName: "Pythium spp.",
    category: "disease",
    affectedPlants: ["All indoor plants", "Monstera", "Snake Plant", "Pothos", "Peace Lily"],
    symptoms: ["Yellowing droopy leaves despite wet soil", "Mushy dark brown foul-smelling roots", "Stem collapse at soil line"],
    treatment: "Unpot immediately, wash away old soil, trim all black mushy roots with sterilized scissors, repot in fresh sterile well-draining soil with perlite.",
    prevention: "Use pots with drainage holes, allow top 2 inches of soil to dry before re-watering, use chunky aroid mix.",
    imageUrl: "https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=600&auto=format&fit=crop&q=80",
    isActive: true,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "kb_05",
    name: "Iron Chlorosis (Nutrient Deficiency)",
    type: "nutrient_deficiency",
    scientificName: "Nutrient Deficiency Fe",
    category: "deficiency",
    affectedPlants: ["Citrus", "Gardenia", "Hibiscus", "Blueberry", "Roses"],
    symptoms: ["Interveinal chlorosis: leaves turn pale yellow while veins remain sharply dark green", "Younger leaves affected first"],
    treatment: "Apply chelated iron (Fe-EDDHA for alkaline soils or Fe-EDTA for neutral soils) as a drench or foliar spray.",
    prevention: "Test and correct soil pH to 6.0 - 6.5. Avoid waterlogged soils which inhibit iron uptake.",
    imageUrl: "https://images.unsplash.com/photo-1584589167171-541ce45f1eea?w=600&auto=format&fit=crop&q=80",
    isActive: true,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "kb_06",
    name: "Rose Black Spot (Diplocarpon rosae)",
    type: "disease",
    scientificName: "Diplocarpon rosae",
    category: "disease",
    affectedPlants: ["Garden Roses", "Miniature Roses", "Shrub Roses"],
    symptoms: ["Circular black spots with fringed margins on upper leaf surfaces", "Surrounding tissue yellows rapidly and leaves drop"],
    treatment: "Collect and dispose of all fallen leaves. Spray with trifloxystrobin or neem-copper combination.",
    prevention: "Water only at base; never wet rose leaves in afternoon or evening. Mulch well.",
    imageUrl: "https://images.unsplash.com/photo-1496062031456-07b8f162a322?w=600&auto=format&fit=crop&q=80",
    isActive: true,
    lastUpdated: new Date().toISOString(),
  }
];

export const SEED_MODEL_METADATA: ModelMetadata[] = [
  {
    id: "mdl_v2_gemini_flash",
    name: "Plantinia Multimodal Vision v2.1",
    version: "2.1.0",
    type: "disease_detection",
    status: "active",
    accuracy: 97.2,
    trainedOn: "84,500 curated botanical samples",
    classes: ["Late Blight", "Powdery Mildew", "Spider Mites", "Healthy", "Root Rot"],
    isActive: true,
    description: "Gemini Vision multimodal engine tuned for plant pathology and rapid foliar diagnosis.",
    lastUpdated: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
    registeredAt: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: "mdl_v1_custom_yolo",
    name: "Plantinia-YOLOv8x Disease Detector",
    version: "1.4.0",
    type: "disease_detection",
    status: "staging",
    accuracy: 94.8,
    trainedOn: "52,000 leaf symptom bounding-box annotations",
    classes: ["Fungal Lesion", "Bacterial Spot", "Pest Infestation"],
    isActive: false,
    description: "Edge-optimized real-time bounding box detection model for mobile video streams.",
    lastUpdated: new Date(Date.now() - 14 * 24 * 3600 * 1000).toISOString(),
    registeredAt: new Date(Date.now() - 14 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: "mdl_v1_resnet_classic",
    name: "ResNet-50 Botanical Classifier",
    version: "1.0.0",
    type: "plant_identification",
    status: "deprecated",
    accuracy: 89.1,
    trainedOn: "28,000 botanical archive images",
    classes: ["Solanum lycopersicum", "Monstera deliciosa", "Ficus lyrata", "Ocimum basilicum"],
    isActive: false,
    description: "Legacy botanical species taxonomic classification baseline.",
    lastUpdated: new Date(Date.now() - 120 * 24 * 3600 * 1000).toISOString(),
    registeredAt: new Date(Date.now() - 120 * 24 * 3600 * 1000).toISOString(),
  }
];

export const SEED_INVOICES: Invoice[] = [
  {
    id: "inv_99812",
    userId: "usr_demo_002",
    amount: 399,
    currency: "INR",
    provider: "razorpay",
    providerPaymentId: "pay_N8eYh90812903",
    status: "paid",
    plan: "Pro Gardener Monthly",
    receiptUrl: "#",
    createdAt: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
  }
];
