'use client';

import React, { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { Flower2, Plus, Search, Droplets, Sun, ArrowRight } from 'lucide-react';
import { apiClient } from '@/lib/api-client';

export default function PlantsPage() {
  const [plants,setPlants]=useState<any[]>([]); const [search,setSearch]=useState(''); const [filterLocation,setFilterLocation]=useState('all'); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null);
  useEffect(()=>{(async()=>{try{const res=await apiClient.plants.list();setPlants(Array.isArray(res.plants)?res.plants:[]);}catch(err:any){setError(err?.message||'Unable to load your garden.');}finally{setLoading(false);}})();},[]);
  const filteredPlants=useMemo(()=>{const q=search.trim().toLowerCase();return plants.filter(p=>{const name=String(p.name||'').toLowerCase();const species=String(p.species||'').toLowerCase();const location=String(p.location||'').toLowerCase();return (!q||name.includes(q)||species.includes(q))&&(filterLocation==='all'||location===filterLocation);});},[plants,search,filterLocation]);
  return <div className="space-y-6">
    <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div><h1 className="text-2xl sm:text-3xl font-extrabold text-slate-900 dark:text-white">My Garden Collection</h1><p className="text-xs sm:text-sm text-slate-500 dark:text-slate-400 mt-1">Track health progress, watering cycles, and plant history.</p></div><Link href="/plants/new" className="inline-flex items-center gap-2 px-4 py-2.5 rounded-2xl bg-emerald-600 text-white font-semibold text-xs"><Plus className="w-4 h-4"/>Add New Plant</Link></div>
    <div className="flex flex-col sm:flex-row items-center gap-3"><div className="relative flex-1 w-full"><Search className="w-4 h-4 text-slate-400 absolute left-3.5 top-1/2 -translate-y-1/2"/><input placeholder="Search by nickname or species..." value={search} onChange={e=>setSearch(e.target.value)} className="w-full pl-10 pr-4 py-2 rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-[#111815] text-xs sm:text-sm"/></div><div className="flex gap-2 w-full sm:w-auto overflow-x-auto">{['all','indoor','outdoor','balcony'].map(loc=><button key={loc} onClick={()=>setFilterLocation(loc)} className={`px-3 py-1.5 rounded-xl text-xs font-semibold capitalize whitespace-nowrap ${filterLocation===loc?'bg-emerald-600 text-white':'bg-white dark:bg-[#111815] border border-slate-200 dark:border-slate-800 text-slate-600 dark:text-slate-400'}`}>{loc}</button>)}</div></div>
    {loading?<div className="py-20 text-center text-xs text-slate-400">Loading plants...</div>:error?<div className="rounded-3xl border border-rose-200 bg-rose-50 p-6 text-sm text-rose-700">{error}<button onClick={()=>location.reload()} className="ml-3 underline font-bold">Retry</button></div>:filteredPlants.length===0?<div className="py-16 text-center bg-white dark:bg-[#111815] rounded-3xl border border-slate-200 dark:border-slate-800 p-8"><Flower2 className="w-12 h-12 text-slate-300 mx-auto"/><h3 className="text-sm font-bold text-slate-900 dark:text-white mt-3">{search?'No Plants Found':'Your Garden Is Empty'}</h3><p className="text-xs text-slate-500 mt-1">{search?'Try a different name or species.':'Add your first plant to start tracking its health.'}</p><Link href="/plants/new" className="inline-flex items-center gap-1.5 px-4 py-2 rounded-xl bg-emerald-600 text-white text-xs font-semibold mt-4"><Plus className="w-3.5 h-3.5"/>Add Plant</Link></div>:<div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5">{filteredPlants.map(plant=><Link key={plant.id} href={`/plants/${plant.id}`} className="bg-white dark:bg-[#111815] rounded-3xl border border-slate-200 dark:border-[#223129] overflow-hidden hover:shadow-lg transition-all"><div className="relative aspect-[4/3] w-full bg-slate-100 dark:bg-slate-900 overflow-hidden">{plant.imageUrl?<img src={plant.imageUrl} alt={plant.name||'Plant'} className="w-full h-full object-cover"/>:<div className="w-full h-full flex items-center justify-center"><Flower2 className="w-12 h-12 text-slate-300"/></div>}<span className="absolute top-3 right-3 px-2.5 py-1 rounded-full text-[10px] font-bold bg-emerald-500/90 text-white capitalize">{plant.healthStatus||'unknown'}</span><span className="absolute bottom-3 left-3 px-2 py-0.5 rounded-lg bg-black/60 text-white text-[10px] font-semibold uppercase">{plant.location||'unknown'}</span></div><div className="p-5 space-y-4"><div><h3 className="text-base font-bold text-slate-900 dark:text-white">{plant.name||'Unnamed Plant'}</h3><p className="text-xs text-slate-500 italic mt-0.5">{plant.species||'Species unknown'}</p></div><div className="pt-3 border-t border-slate-100 dark:border-slate-800 flex items-center justify-between text-xs text-slate-500"><span><Droplets className="w-3.5 h-3.5 text-sky-500 inline mr-1"/>Every {plant.wateringFrequencyDays??'?'}d</span><span><Sun className="w-3.5 h-3.5 text-amber-500 inline mr-1"/>{plant.sunlightNeeds||'unknown'}</span><ArrowRight className="w-4 h-4 text-slate-400"/></div></div></Link>)}</div>}
  </div>;
}
