'use client';

import React,{useEffect,useState}from'react';
import Link from'next/link';
import{Camera,Plus,Flower2,AlertTriangle,CalendarCheck,Sparkles,CloudSun,ArrowRight,Droplets}from'lucide-react';
import{apiClient}from'@/lib/api-client';
import{SeverityBadge}from'@/components/diagnosis/SeverityBadge';
import{CameraCaptureModal}from'@/components/camera/CameraCaptureModal';
import{useRouter}from'next/navigation';

export default function DashboardPage(){
 const router=useRouter();const[plants,setPlants]=useState<any[]>([]);const[diagnoses,setDiagnoses]=useState<any[]>([]);const[tasks,setTasks]=useState<any[]>([]);const[weather,setWeather]=useState<any>(null);const[isCameraOpen,setIsCameraOpen]=useState(false);const[loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{try{const[p,w,t,d]=await Promise.all([apiClient.plants.list().catch(()=>({plants:[]})),apiClient.weather.get().catch(()=>({advisory:null})),apiClient.careTasks.list().catch(()=>({tasks:[]})),fetch('/api/diagnose').then(r=>r.ok?r.json():{diagnoses:[]}).catch(()=>({diagnoses:[]}))]);setPlants(Array.isArray(p.plants)?p.plants:[]);setWeather(w.advisory||null);setTasks(Array.isArray(t.tasks)?t.tasks:[]);setDiagnoses(Array.isArray(d.diagnoses)?d.diagnoses:[]);}finally{setLoading(false);}})();},[]);
 const healthy=plants.filter(p=>p.healthStatus==='healthy').length;const healthScore=plants.length?Math.round(healthy/plants.length*100):null;const needsAttention=plants.filter(p=>p.healthStatus!=='healthy').length;const pending=tasks.filter(t=>!t.isCompleted).length;
 const handleCaptured=(url:string,type:'image'|'video')=>{sessionStorage.setItem('plantinia_scan_media',url);sessionStorage.setItem('plantinia_scan_type',type);router.push('/diagnose');};
 if(loading)return <div className="py-20 text-center text-xs text-slate-400">Loading your Plantinia dashboard...</div>;
 return <div className="space-y-6">
  <div className="relative overflow-hidden rounded-3xl bg-gradient-to-br from-emerald-700 via-emerald-800 to-teal-900 text-white p-6 sm:p-8 shadow-xl"><div className="relative z-10 max-w-xl space-y-3"><div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-emerald-500/20 text-emerald-200 border border-emerald-400/30 text-xs font-semibold"><Sparkles className="w-3.5 h-3.5"/>Autonomous Botanical AI</div><h1 className="text-2xl sm:text-3xl font-extrabold">How are your plants thriving today?</h1><p className="text-emerald-100/80 text-xs sm:text-sm">Run a multimodal plant diagnosis or manage your tracked garden.</p><div className="flex flex-wrap gap-3 pt-2"><button onClick={()=>setIsCameraOpen(true)} className="inline-flex items-center gap-2 px-5 py-2.5 rounded-2xl bg-white text-emerald-950 font-bold text-sm"><Camera className="w-4 h-4"/>Diagnose Leaf Now</button><Link href="/plants/new" className="inline-flex items-center gap-2 px-4 py-2.5 rounded-2xl bg-emerald-600/60 border border-emerald-400/40 text-white font-semibold text-sm"><Plus className="w-4 h-4"/>Add Plant</Link></div></div><Flower2 className="absolute right-0 -bottom-10 w-80 h-80 opacity-15 pointer-events-none"/></div>
  <div className="grid grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-4">
   <div className="p-4 rounded-2xl bg-white dark:bg-[#111815] border border-slate-200 dark:border-[#223129]"><span className="text-xs text-slate-500">Health Score</span><div className="text-2xl sm:text-3xl font-extrabold text-emerald-600 mt-2">{healthScore===null?'—':`${healthScore}%`}</div><p className="text-[11px] text-slate-500 mt-1">{plants.length?`${plants.length} specimens monitored`:'No plants tracked yet'}</p></div>
   <div className="p-4 rounded-2xl bg-white dark:bg-[#111815] border border-slate-200 dark:border-[#223129]"><span className="text-xs text-slate-500">Needs Attention</span><div className="text-2xl sm:text-3xl font-extrabold text-amber-600 mt-2">{needsAttention}</div><p className="text-[11px] text-slate-500 mt-1">tracked plants</p></div>
   <div className="p-4 rounded-2xl bg-white dark:bg-[#111815] border border-slate-200 dark:border-[#223129]"><span className="text-xs text-slate-500">Tasks Today</span><div className="text-2xl sm:text-3xl font-extrabold text-slate-900 dark:text-white mt-2">{pending}</div><p className="text-[11px] text-slate-500 mt-1">pending reminders</p></div>
   <div className="p-4 rounded-2xl bg-white dark:bg-[#111815] border border-slate-200 dark:border-[#223129]"><span className="text-xs text-slate-500">Microclimate</span><div className="text-2xl sm:text-3xl font-extrabold text-slate-900 dark:text-white mt-2">{weather?`${weather.temperatureC}°C`:'—'}</div><p className="text-[11px] text-slate-500 mt-1">{weather?.condition||'Weather unavailable'}</p></div>
  </div>
  <div className="grid grid-cols-1 lg:grid-cols-3 gap-6"><div className="lg:col-span-2 space-y-6">
   <div className="bg-white dark:bg-[#111815] p-5 rounded-3xl border border-slate-200 dark:border-[#223129]"><div className="flex justify-between mb-4"><div><h3 className="font-bold text-slate-900 dark:text-white">My Garden</h3><p className="text-xs text-slate-500">Tracked plants</p></div><Link href="/plants" className="text-xs font-semibold text-emerald-600">View All ({plants.length}) <ArrowRight className="w-3.5 h-3.5 inline"/></Link></div>{plants.length===0?<div className="py-8 text-center text-xs text-slate-400">No plants tracked yet. Add your first plant to start a garden.</div>:<div className="grid grid-cols-1 sm:grid-cols-2 gap-3">{plants.slice(0,4).map(p=><Link key={p.id} href={`/plants/${p.id}`} className="flex items-center gap-3 p-3 rounded-2xl border border-slate-100 dark:border-[#1e2a24]"><div className="w-14 h-14 rounded-xl bg-slate-100 flex items-center justify-center overflow-hidden">{p.imageUrl?<img src={p.imageUrl} alt={p.name||'Plant'} className="w-full h-full object-cover"/>:<Flower2 className="w-7 h-7 text-slate-300"/>}</div><div className="min-w-0"><h4 className="text-sm font-bold truncate text-slate-900 dark:text-white">{p.name||'Unnamed Plant'}</h4><p className="text-xs text-slate-500 italic truncate">{p.species||'Species unknown'}</p><span className="text-[11px] text-slate-400"><Droplets className="w-3 h-3 inline mr-1"/>Every {p.wateringFrequencyDays??'?'} days</span></div></Link>)}</div>}</div>
   <div className="bg-white dark:bg-[#111815] p-5 rounded-3xl border border-slate-200 dark:border-[#223129]"><div className="flex justify-between mb-4"><div><h3 className="font-bold text-slate-900 dark:text-white">Recent AI Diagnoses</h3><p className="text-xs text-slate-500">Standalone and garden-linked scans</p></div><Link href="/history" className="text-xs font-semibold text-emerald-600">History <ArrowRight className="w-3.5 h-3.5 inline"/></Link></div>{diagnoses.length===0?<div className="py-8 text-center text-xs text-slate-400">No scans recorded yet.</div>:<div className="space-y-3">{diagnoses.slice(0,3).map(d=><Link key={d.id} href={`/diagnose/result/${d.id}`} className="flex items-center justify-between gap-3 p-3 rounded-2xl border border-slate-100 dark:border-[#1e2a24]"><div className="flex items-center gap-3"><div className="w-12 h-12 rounded-xl bg-slate-100 overflow-hidden">{d.mediaUrl&&<img src={d.mediaUrl} alt="Diagnosis scan" className="w-full h-full object-cover"/>}</div><div><h4 className="text-sm font-bold text-slate-900 dark:text-white">{d.diseaseName}</h4><p className="text-xs text-slate-500">{d.identifiedSpecies} • {d.confidence}%</p></div></div><SeverityBadge severity={d.severity}/></Link>)}</div>}</div>
  </div><div className="space-y-6"><div className="p-5 rounded-3xl bg-white dark:bg-[#111815] border border-slate-200 dark:border-[#223129]"><h3 className="font-bold text-slate-900 dark:text-white mb-3">Care Schedule</h3><p className="text-xs text-slate-500">{pending?`${pending} care task${pending===1?'':'s'} pending.`:'No pending care tasks.'}</p><Link href="/care-plans" className="text-xs font-semibold text-emerald-600 inline-block mt-3">Open schedule →</Link></div>{weather&&<div className="p-5 rounded-3xl bg-sky-50 dark:bg-sky-950/30 border border-sky-100 dark:border-sky-900/40"><div className="flex items-center gap-2"><CloudSun className="w-5 h-5 text-sky-500"/><span className="text-xs font-bold uppercase text-sky-700">Microclimate</span></div><p className="text-2xl font-extrabold text-slate-900 dark:text-white mt-2">{weather.temperatureC}°C</p><p className="text-xs text-slate-500">{weather.location} • {weather.fungalRisk||'unknown'} fungal risk</p></div>}</div></div>
  <CameraCaptureModal isOpen={isCameraOpen} onClose={()=>setIsCameraOpen(false)} onMediaSelected={handleCaptured}/>
 </div>;
}
