'use client';

import React,{useEffect,useState}from'react';
import{CreditCard,CheckCircle2,AlertCircle,Loader2,ArrowRight}from'lucide-react';
import{apiClient}from'@/lib/api-client';

export default function BillingPage(){
 const[plans,setPlans]=useState<any[]>([]);const[currentTier,setCurrentTier]=useState('free');const[credits,setCredits]=useState(0);const[videoCredits,setVideoCredits]=useState(0);const[plantsCount,setPlantsCount]=useState(0);const[invoices,setInvoices]=useState<any[]>([]);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState<string|null>(null);const[error,setError]=useState<string|null>(null);const[message,setMessage]=useState<string|null>(null);const[razorpayReady,setRazorpayReady]=useState(false);
 const load=async()=>{setLoading(true);setError(null);try{const r=await apiClient.billing.getPlans();setPlans(Array.isArray(r.plans)?r.plans:[]);setCurrentTier(r.currentTier||'free');setCredits(r.creditsRemaining??0);setVideoCredits(r.videoCreditsRemaining??0);setPlantsCount(r.plantsCount??0);setInvoices(Array.isArray(r.invoices)?r.invoices:[]);}catch(e:any){setError(e?.message||'Unable to load billing information.');}finally{setLoading(false);}};
 useEffect(()=>{void load();const script=document.createElement('script');script.src='https://checkout.razorpay.com/v1/checkout.js';script.async=true;script.onload=()=>setRazorpayReady(true);script.onerror=()=>setRazorpayReady(false);document.body.appendChild(script);return()=>{script.remove();};},[]);
 const razorpay=async(tier:string)=>{if(tier==='free'||tier===currentTier)return;if(!razorpayReady){setError('Razorpay checkout is still loading. Please try again in a moment.');return;}setBusy(tier);setError(null);setMessage(null);try{const r=await apiClient.billing.createRazorpayOrder(tier);const R=(window as any).Razorpay;if(!R)throw new Error('Razorpay checkout is unavailable.');const checkout=new R({key:r.keyId,amount:r.order.amount,currency:r.order.currency||'INR',name:'Plantinia AI Plant Doctor',description:`Upgrade to ${r.plan.name}`,order_id:r.order.id,handler:async(response:any)=>{try{const verified=await apiClient.billing.verifyRazorpayPayment({razorpay_order_id:response.razorpay_order_id,razorpay_payment_id:response.razorpay_payment_id,razorpay_signature:response.razorpay_signature,tier});setMessage(verified.message||'Payment verified.');await load();}catch(e:any){setError(e?.message||'Payment verification failed.');}finally{setBusy(null);}}});checkout.on?.('payment.failed',()=>{setError('Payment was not completed.');setBusy(null);});checkout.open();}catch(e:any){setError(e?.message||'Unable to start checkout.');setBusy(null);}};
 const stripe=async(tier:string)=>{setBusy(tier);setError(null);try{const r=await apiClient.billing.createStripeSession(tier);if(!r.url)throw new Error('Stripe checkout URL was not returned.');window.location.assign(r.url);}catch(e:any){setError(e?.message||'Unable to start Stripe checkout.');setBusy(null);}};
 if(loading)return <div className="py-20 text-center text-xs text-slate-400">Loading plans and billing...</div>;
 return <div className="max-w-6xl mx-auto space-y-8"><div><div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-emerald-100 dark:bg-emerald-950/60 text-emerald-800 dark:text-emerald-300 text-xs font-semibold mb-2"><CreditCard className="w-3.5 h-3.5"/>Subscriptions & Monetization</div><h1 className="text-2xl sm:text-3xl font-extrabold text-slate-900 dark:text-white">Plans & Billing</h1><p className="text-xs sm:text-sm text-slate-500 mt-1">Your plan, entitlements, and verified payment options.</p></div>
 {error&&<div className="p-4 rounded-2xl bg-rose-50 dark:bg-rose-950/30 border border-rose-200 dark:border-rose-900 text-xs text-rose-700 dark:text-rose-300"><AlertCircle className="w-4 h-4 inline mr-2"/>{error}</div>}{message&&<div className="p-4 rounded-2xl bg-emerald-50 dark:bg-emerald-950/30 border border-emerald-200 dark:border-emerald-900 text-xs text-emerald-700 dark:text-emerald-300"><CheckCircle2 className="w-4 h-4 inline mr-2"/>{message}</div>}
 <div className="p-6 rounded-3xl bg-white dark:bg-[#111815] border border-slate-200 dark:border-[#223129] grid grid-cols-2 md:grid-cols-4 gap-4"><div><span className="text-[11px] text-slate-400">Current plan</span><strong className="block text-lg capitalize text-slate-900 dark:text-white">{currentTier}</strong></div><div><span className="text-[11px] text-slate-400">Leaf scans</span><strong className="block text-lg text-emerald-600">{currentTier==='pro'||currentTier==='farm'?'Unlimited':credits}</strong></div><div><span className="text-[11px] text-slate-400">Video scans</span><strong className="block text-lg text-emerald-600">{currentTier==='pro'||currentTier==='farm'?'Unlimited':videoCredits}</strong></div><div><span className="text-[11px] text-slate-400">Tracked plants</span><strong className="block text-lg text-slate-900 dark:text-white">{plantsCount}</strong></div></div>
 <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5 gap-5">{plans.map(plan=>{const current=currentTier===plan.id;return <div key={plan.id} className="rounded-3xl p-5 bg-white dark:bg-[#111815] border border-slate-200 dark:border-[#223129] flex flex-col"><div><h3 className="font-bold text-slate-900 dark:text-white">{plan.name}</h3><p className="text-xs text-slate-500 mt-1 min-h-8">{plan.description}</p><div className="text-2xl font-extrabold text-slate-900 dark:text-white mt-4">{plan.priceINR===0?'Free':`₹${plan.priceINR}`}<span className="text-[11px] text-slate-400 font-normal">{plan.priceINR?'/mo':''}</span></div><ul className="mt-4 pt-4 border-t border-slate-100 dark:border-slate-800 space-y-2">{(plan.features||[]).map((f:string,i:number)=><li key={i} className="text-xs text-slate-600 dark:text-slate-300"><CheckCircle2 className="w-3.5 h-3.5 inline text-emerald-600 mr-1"/>{f}</li>)}</ul></div><div className="mt-auto pt-5">{current?<button disabled className="w-full py-2.5 rounded-xl bg-slate-100 dark:bg-slate-800 text-slate-400 text-xs font-bold">Current Plan</button>:plan.id==='free'?<button disabled className="w-full py-2.5 rounded-xl bg-slate-100 dark:bg-slate-800 text-slate-400 text-xs">Free plan</button>:<><button onClick={()=>void razorpay(plan.id)} disabled={busy===plan.id||!razorpayReady} className="w-full py-2.5 rounded-xl bg-emerald-600 text-white text-xs font-bold disabled:opacity-50">{busy===plan.id?<Loader2 className="w-4 h-4 animate-spin mx-auto"/>:razorpayReady?`Pay with UPI • ₹${plan.priceINR}`:'Loading checkout…'}</button>{plan.priceUSD>0&&<button onClick={()=>void stripe(plan.id)} disabled={busy===plan.id} className="w-full mt-2 py-2 text-[11px] text-slate-400 hover:text-slate-700 dark:hover:text-slate-200">or pay with Stripe (${plan.priceUSD}) <ArrowRight className="w-3 h-3 inline"/></button>}</>}</div></div>})}</div>
 <div className="p-6 rounded-3xl bg-white dark:bg-[#111815] border border-slate-200 dark:border-[#223129]"><h3 className="font-bold text-slate-900 dark:text-white mb-4">Billing History & Invoices</h3>{invoices.length===0?<p className="text-xs text-slate-400 text-center py-4">No past payment receipts found.</p>:<div className="divide-y divide-slate-100 dark:divide-slate-800">{invoices.map(inv=><div key={inv.id} className="py-3 flex justify-between text-xs"><div><strong className="text-slate-900 dark:text-white">{inv.plan}</strong><p className="text-slate-400">{inv.provider} • {inv.status}</p></div><span className="font-semibold text-slate-700 dark:text-slate-300">{inv.amount} {inv.currency}</span></div>)}</div>}</div>
 </div>;
}
