'use client';

import React, { useEffect, useState } from 'react';
import { CalendarCheck, Plus, CheckCircle2, AlertCircle } from 'lucide-react';
import { apiClient } from '@/lib/api-client';

export default function CarePlansPage() {
  const [tasks,setTasks]=useState<any[]>([]); const [plants,setPlants]=useState<any[]>([]); const [filter,setFilter]=useState<'pending'|'completed'|'all'>('pending');
  const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const [actionError,setActionError]=useState<string|null>(null);
  const [isModalOpen,setIsModalOpen]=useState(false); const [title,setTitle]=useState(''); const [category,setCategory]=useState('water'); const [dueDate,setDueDate]=useState(new Date().toISOString().split('T')[0]); const [selectedPlantId,setSelectedPlantId]=useState('');

  useEffect(()=>{void loadData();},[]);
  async function loadData(){setLoading(true);setError(null);try{const [tRes,pRes]=await Promise.all([apiClient.careTasks.list(),apiClient.plants.list()]);setTasks(Array.isArray(tRes.tasks)?tRes.tasks:[]);setPlants(Array.isArray(pRes.plants)?pRes.plants:[]);}catch(err:any){setError(err?.message||'Unable to load your care schedule.');}finally{setLoading(false);}}
  async function handleToggle(id:string){setActionError(null);try{const res=await apiClient.careTasks.toggle(id);if(res.task)setTasks(prev=>prev.map(t=>t.id===id?res.task:t));}catch(err:any){setActionError(err?.message||'Unable to update that reminder.');}}
  async function handleCreateTask(e:React.FormEvent){e.preventDefault();if(!title.trim())return;setActionError(null);const plant=plants.find(p=>p.id===selectedPlantId);try{const res=await apiClient.careTasks.create({title:title.trim(),category,dueDate,plantId:selectedPlantId||undefined,plantName:plant?.name});if(res.task)setTasks(prev=>[...prev,res.task]);setIsModalOpen(false);setTitle('');}catch(err:any){setActionError(err?.message||'Unable to create the reminder.');}}
  const filtered=tasks.filter(t=>filter==='pending'?!t.isCompleted:filter==='completed'?t.isCompleted:true);

  return <div className="max-w-3xl mx-auto space-y-6">
    <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div><h1 className="text-2xl sm:text-3xl font-extrabold text-slate-900 dark:text-white">Garden Care Schedule</h1><p className="text-xs sm:text-sm text-slate-500 dark:text-slate-400 mt-1">Watering, spraying, fertilizing, pruning, and inspection reminders.</p></div><button onClick={()=>setIsModalOpen(true)} className="inline-flex items-center gap-1.5 px-4 py-2.5 rounded-2xl bg-emerald-600 hover:bg-emerald-700 text-white font-semibold text-xs"><Plus className="w-4 h-4"/>Add Reminder</button></div>
    {actionError&&<div className="p-3 rounded-2xl bg-rose-50 dark:bg-rose-950/30 border border-rose-200 dark:border-rose-900 text-rose-700 dark:text-rose-300 text-xs">{actionError}</div>}
    <div className="flex gap-2 border-b border-slate-200 dark:border-slate-800 pb-2">{(['pending','completed','all'] as const).map(f=><button key={f} onClick={()=>setFilter(f)} className={`px-3 py-1.5 rounded-xl text-xs font-semibold capitalize ${filter===f?'bg-emerald-600 text-white':'text-slate-600 dark:text-slate-400'}`}>{f==='pending'?`Pending Tasks (${tasks.filter(t=>!t.isCompleted).length})`:f}</button>)}</div>
    {loading?<div className="py-20 text-center text-xs text-slate-400">Loading schedule...</div>:error?<div className="rounded-3xl border border-rose-200 dark:border-rose-900 bg-rose-50 dark:bg-rose-950/30 p-6 text-sm text-rose-700 dark:text-rose-300">{error}<button onClick={()=>void loadData()} className="ml-3 font-bold underline">Retry</button></div>:filtered.length===0?<div className="text-center py-16 bg-white dark:bg-[#111815] rounded-3xl border border-slate-200 dark:border-slate-800 p-8"><CalendarCheck className="w-12 h-12 text-slate-300 mx-auto mb-2"/><h3 className="text-sm font-bold text-slate-900 dark:text-white">No reminders in this view</h3><p className="text-xs text-slate-500 mt-1">Create a reminder when you need to track a care action.</p></div>:<div className="space-y-3">{filtered.map(task=><button key={task.id} type="button" onClick={()=>void handleToggle(task.id)} className={`w-full text-left flex items-start gap-3 p-4 rounded-2xl border transition-all ${task.isCompleted?'bg-slate-50 dark:bg-[#121915] border-slate-200 opacity-60':'bg-white dark:bg-[#111815] border-slate-200 dark:border-[#223129] hover:border-emerald-400'}`}><CheckCircle2 className={`mt-0.5 w-5 h-5 shrink-0 ${task.isCompleted?'text-emerald-500':'text-slate-300'}`}/><div className="flex-1 min-w-0"><div className="flex items-center justify-between gap-3"><h4 className={`text-sm font-bold ${task.isCompleted?'line-through text-slate-400':'text-slate-900 dark:text-white'}`}>{task.title}</h4><span className="text-[11px] font-semibold text-slate-400 whitespace-nowrap">Due {task.dueDate}</span></div><div className="flex items-center gap-3 mt-1.5 text-xs text-slate-500"><span className="capitalize">{task.category}</span>{task.plantName&&<span className="font-semibold text-emerald-600">{task.plantName}</span>}</div></div></button>)}</div>}

    {isModalOpen&&<div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60"><div className="w-full max-w-md bg-white dark:bg-[#111815] rounded-3xl p-6 shadow-2xl"><h3 className="text-base font-bold text-slate-900 dark:text-white mb-4">Add Care Reminder</h3><form onSubmit={handleCreateTask} className="space-y-4"><input required value={title} onChange={e=>setTitle(e.target.value)} placeholder="Task title" className="w-full p-2.5 rounded-xl border bg-slate-50 dark:bg-[#18231d] text-xs"/><select value={selectedPlantId} onChange={e=>setSelectedPlantId(e.target.value)} className="w-full p-2.5 rounded-xl border bg-slate-50 dark:bg-[#18231d] text-xs"><option value="">General Garden</option>{plants.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><div className="grid grid-cols-2 gap-3"><select value={category} onChange={e=>setCategory(e.target.value)} className="w-full p-2.5 rounded-xl border bg-slate-50 dark:bg-[#18231d] text-xs"><option value="water">Watering</option><option value="spray">Foliar Spray</option><option value="fertilize">Fertilizer</option><option value="prune">Pruning</option><option value="inspect">Pest Inspection</option></select><input type="date" value={dueDate} onChange={e=>setDueDate(e.target.value)} className="w-full p-2.5 rounded-xl border bg-slate-50 dark:bg-[#18231d] text-xs"/></div><div className="flex justify-end gap-2"><button type="button" onClick={()=>setIsModalOpen(false)} className="px-4 py-2 rounded-xl text-xs">Cancel</button><button type="submit" className="px-4 py-2 rounded-xl bg-emerald-600 text-white text-xs font-semibold">Schedule Task</button></div></form></div></div>}
  </div>;
}
